site:
  name: example

global:
  pattern: multicluster-devsecops
  repoURL: "https://github.com/pattern-clone/multicluster-devsecops"
  targetRevision: main
  ciNamespace: devsecops-ci

  git:
    hostname: github.com
    account: PLAINTEXT
    username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main

  imageregistry:
    account: PLAINTEXT
    hostname: quay.io
    type: quay

devel:
  appURL: AUTOMATED
  image: AUTOMATED
  roxCTLImage: registry.redhat.io/rh-acs/roxctl:3.0.62.0
  
clusterGroup:
  name: testgroup

