# Possibly still not the right home...
devel: 

  image: chat-client:latest
  npmbase: quay.io/hybridcloudpatterns/ubi-npm
  namespace: devsecops-ci
  roxCTLImage: registry.access.redhat.com/advanced-cluster-security/rhacs-roxctl-rhel8:3.71.0-5

global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

clusterGroup:
  name: development
  isHubCluster: false
  clusterName: PROVIDE_CLUSTERNAME

  namespaces:
    - stackrox
    - policies
    - openshift-pipelines
    - devsecops-ci
    - config-demo

  subscriptions:
    rhacs-operator:
      name: rhacs-operator  #packageName
      namespace: openshift-operators # operator namespace
      channel: rhacs-3.71

    openshift-pipelines:
      name: openshift-pipelines-operator-rh
      namespace: openshift-operators
      channel: pipelines-1.7

    quay-bridge-operator:
      name: quay-bridge-operator
      namespace: openshift-operators
      channel: stable-3.7

  projects:
    - secured
    - ci
    - test-app

  applications:
    acs-secured:
      name: acs-secured
      namespace: stackrox
      project: secured
      path: charts/hub/acs/secured

    argo-rollouts:
      name: argo-rollouts
      namespace: argo-rollouts
      project: rollouts
      path: charts/region/rollouts

    pipelines:
      name: pipelines
      namespace: devsecops-ci
      project: ci
      path: charts/region/pipelines
      ignoreDifferences:
      - kind: ServiceAccount
        jsonPointers:
        - /imagePullSecrets
        - /secrets

    quay-integration:
      name: quay-integration
      namespace: openshift-operators
      project: secured
      path: charts/region/quay

    acs-integration:
      name: acs-integration
      namespace: stackrox
      project: ci
      path: charts/region/acs

    nexus:
      name: nexus
      namespace: 
      project: ci
      path: charts/region/mcdso-tools/nexus

    reports-repo:
      name: reports-repo
      namespace: 
      project: ci
      path: charts/region/mcdso-tools/reports

    sonarqube:
      name: sonarqube
      namespace: 
      project: ci
      path: charts/region/mcdso-tools/sonarqube

#Adding jchraibi #advanced-devsecops to pattern framework
    staging-spring-petclinic:
      name: staging-spring-petclinic
      namespace: devsecops-qa
      project: spring-petclinic
      path: charts/region/stage/spring-petclinic-config

#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#  - name: pipelines
#    namespace: production
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: stable
#    overrides:
#    - name: myparam
#      value: myparam
#
#  - name: pipelines
#    namespace: staging
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: main
