apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: react-build
  namespace: {{ .Values.global.ciNamespace }}
spec:
  workspaces:
    - name: output
  params:
    - name: TLSVERIFY
      type: string
      default: 'true'
    - name: IMAGE
      type: string
      default: '{{ .Values.devel.image }}'
    - name: DOCKERFILE
      type: string
      default: ./Dockerfile
    - name: CONTEXT
      type: string
      default: .
  steps:
  - name: install
    image: {{ .Values.devel.npmbase }}
    command:
    - /usr/bin/npm
    args:
    - install
    workingDir: $(workspaces.output.path)
  - name: build
    image: {{ .Values.devel.image }}
    command:
    - /usr/bin/npm
    args:
    - run-script
    - build
    workingDir: $(workspaces.output.path)
