apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: react-scan-pipelinerun
spec:
  params: 
    - name: "github-repo-revision"
      value: "main"
    - name: "github-repo-url"
      value: {{ .Values.devel.appURL }}
    - name: "context-dir"
      value: "/"
    - name: "image-name"
      value: {{ .Values.devel.image }}
    - name: "is-name"
      value: "chat-client"
    - name: "acs-image"
      value: {{ .Values.devel.image }}
    - name: "acs-scan-api"
      value: "https://central-stackrox.{{ .Values.global.hubClusterDomain }}"
  pipelineRef:
    name: build-scan-and-deploy
  podTemplate:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      volumes:
        - name: varlibcontainers
          persistentVolumeClaim:
            claimName: containers-pvc
  serviceAccountName: pipeline-svc
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: pipeline-pvc